# Creating NumPy Arrays

In [1]:
# import numpy as np

In Julia, the direct equivalent to NumPy arrays from Python is simply Julia's native array type. Julia's built-in array functionality is comprehensive and includes many features for numerical computation that NumPy provides in Python. Julia arrays are natively multidimensional and can perform many operations that you would typically use NumPy for, such as element-wise operations, matrix algebra, and broadcasting, without the need for an external library.

### Key Similarities

- **Multidimensional**: Both Julia arrays and NumPy arrays can have any number of dimensions.
- **Indexing and Slicing**: Julia arrays use 1-based indexing (similar to MATLAB and Fortran), while NumPy arrays are 0-based. Despite this difference, both support sophisticated indexing and slicing mechanisms.
- **Broadcasting**: Both Julia and NumPy support broadcasting, allowing you to perform vectorized operations on arrays of different shapes. In Julia, broadcasting is indicated by dot syntax (e.g., `.+`, `.*`).
- **Type-Agnostic**: Both systems allow arrays to hold any type of data, though they are most commonly used for numerical data. Both also support specifying the data type of the array elements.

### Key Differences

- **1-Based Indexing**: As mentioned, Julia uses 1-based indexing, which is the main syntactical difference from Python's 0-based indexing.
- **Performance**: Julia is designed with performance in mind, especially for numerical computing. While NumPy is highly optimized and often uses C under the hood for performance, Julia's native arrays benefit directly from the language's performance characteristics without needing to bridge to C.
- **Syntax and Language Integration**: Julia's syntax for array operations is more integrated into the language itself, avoiding the need for an external library for basic and advanced numerical operations.

### Examples

Creating and manipulating arrays in Julia:

```julia
# Creating a 1D array
a = [1, 2, 3, 4, 5]

# Creating a 2D array (matrix)
b = [1 2 3; 4 5 6; 7 8 9]

# Element-wise operations (broadcasting)
c = a .+ 1

# Matrix multiplication
d = b * b
```

These examples show how Julia's native arrays can be used in a way that's conceptually similar to how NumPy arrays are used in Python, with some differences in syntax and functionality reflecting the distinct design philosophies of Julia and Python.

---

&#x1F3F7; To achieve the same functionality in Julia as the Python code you've provided, which involves creating a range and inspecting its elements and shape, you would use the following Julia code:

In this Julia code:
- `0:9` creates a range object, similar to `np.arange(10)` in Python. However, Julia's range includes the start and is exclusive of the end by default, which aligns with the Python `range` behavior. To get an array from this range, we use `collect(a1)`.
- `println` is used for printing in Julia, similar to `print` in Python.
- `size(a1_array)` gives the dimensions of the array, which is similar to `.shape` in Python's NumPy arrays.

In [2]:
range_a1 = 0:9 # creates a range from 0 to 9

# To create an array from the range and print it
a1 = collect(range_a1)
println(a1)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Print the shape (dimensions) of the array
println(size(a1))  # (10,)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
(10,)


In [3]:
# Create a range from 0 to 8 with a step of 2
range_a2 = 0:2:8

# To create an array from the range and print it
a2 = collect(range_a2)
println(a2)  # [0, 2, 4, 6, 8]

[0, 2, 4, 6, 8]


In [4]:
a3 = zeros(5)             # create an array with all 0s
println(a3)               # [ 0.  0.  0.  0.  0.]
println(size(a3))         # (5,)

[0.0, 0.0, 0.0, 0.0, 0.0]
(5,)


In [5]:
a4 = zeros(2, 3)          # array of rank 2 with all 0s; 2 rows and 3 columns
println(size(a4))         # (2,3)
a4

(2, 3)


2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [6]:
# Create a 2-dimensional array of 2 rows and 3 columns, filled with 8s
a5 = fill(8, (2, 3))     # array of rank 2 with all 8s
a5

2×3 Matrix{Int64}:
 8  8  8
 8  8  8

In [7]:
using LinearAlgebra


In [8]:
a6 = LinearAlgebra.I(4)                # 4x4 identity matrix
a6

4×4 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅  ⋅
 ⋅  1  ⋅  ⋅
 ⋅  ⋅  1  ⋅
 ⋅  ⋅  ⋅  1

In [9]:
a7 = rand(2, 4)              # rank 2 array (2 rows 4 columns) with random values
                             # in the half-open interval [0.0, 1.0)
a7

2×4 Matrix{Float64}:
 0.0450877  0.243293  0.675673  0.0709491
 0.155687   0.620302  0.963692  0.13209

In [10]:
list1 = [1,2,3,4,5]  # list1 is a list in Julia
# In Julia, the list itself is already an array, so we can use it directly
r1 = list1           # rank 1 array
println(r1)          # [1 2 3 4 5]
println(size(r1))

[1, 2, 3, 4, 5]
(5,)


## Array Indexing

&#x1F3F7;   In Julia, arrays are `1-based indexing` (like MatLab), which means that the first element of an array is accessed with index 1, not 0 as in Python. Additionally, Julia does not support negative indexing directly as Python does. To access elements from the end of an array in Julia, you can use the `end` keyword or calculate the position from the length of the array. Here's how you can achieve the equivalent in Julia:

This approach correctly accesses the first and second elements using `1-based indexing` and accesses the last and second-to-last elements using `end` and `end-1`, respectively.

In [11]:
println(r1[1])       # 1
println(r1[2])       # 2

# No negative indexing, Print elements from the end of the array
println(r1[end])     # 5, equivalent to r1[-1] in Python
println(r1[end-1])   # 4, equivalent to r1[-2] in Python

1
2
5
4


In [12]:
list2 = [6,7,8,9,0]

# Create a rank 2 matrix from the two lists
# This stacks vertically
# r2 = [list1 list2]  # This stacks vertically. you can also use hcat(list1, list2)
# @show (r2 == vcat(list1, list2))

r2 = transpose([list1 list2]) # rank 2 matrix
# r2 = vcat(transpose(list1), transpose(list2))

println(r2)

# Print the shape (dimensions) of the array
println(size(r2))             # (2,5) - 2 rows and 5 columns  

# Access and print specific elements using Julia's 1-based indexing
println(r2[1, 1])             # 1
println(r2[1, 2])             # 2
println(r2[2, 1])             # 6
r2

[1 2 3 4 5; 6 7 8 9 0]
(2, 5)
1
2
6


2×5 transpose(::Matrix{Int64}) with eltype Int64:
 1  2  3  4  5
 6  7  8  9  0

In [13]:
list1 = [1,2,3,4,5]
r1 = vec(list1)                 # transform to vector
println(r1[[3, 5]])             # [3 5]  1-indexed based

[3, 5]


## Boolean Indexing

In [14]:
println(r1 .> 2)     # [False False  True  True  True]


Bool[0, 0, 1, 1, 1]


In [15]:
println(r1[r1 .> 2]) # [3 4 5]

[3, 4, 5]


# Exercises
***


1. Print out all the odd number items in the r1 array
2. Print out the last third number in the r1 array

# Solutions
---

In [16]:
println(r1[r1 .% 2 .== 1])
println(r1[end-2])      # -3 in Python (0-based indexing)

[1, 3, 5]
3


---


In [17]:
nums = collect(0:19) # np.arange(20) if forcing 0-based index
println(nums)        # [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [18]:
odd_num = nums[nums .% 2 .== 1]
println(odd_num)     # [ 1  3  5  7  9 11 13 15 17 19]

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


## Slicing Arrays

In [19]:
a = [1 2 3 4 5; 
     4 5 6 7 8; 
     9 8 7 6 5]  # rank 3 array
a

3×5 Matrix{Int64}:
 1  2  3  4  5
 4  5  6  7  8
 9  8  7  6  5

In [20]:
b1 = a[2:3, 1:3]            # row 2 to 3 (inclusive) and first 3 columns
println(b1)                 # in Python row 1 to 3 (not inclusive) and first 3 columns
b1

[4 5 6; 9 8 7]


2×3 Matrix{Int64}:
 4  5  6
 9  8  7

In [21]:
b2 = a[end-1:end, end-1:end]   # Select the last two rows and the last two columns
println(b2)                    # In python b2 = a[-2:,-2:]
b2

[7 8; 6 5]


2×2 Matrix{Int64}:
 7  8
 6  5

## NumPy Slice Is a Reference

&#x1F3F7;   In Julia, slicing an array creates a copy, so modifications to the slice do not affect the original array. To modify the original array through a slice, use a view with `view` function or `@view` macro.

In [22]:
b3 = @view a[2:end, 3:end] # row 2 onwards and column 3 onwards (1-based index)
                           # In Python: row 1 onwards and column 2 onwards (0-based index)
                           # b3 is now pointing to a subset of a7
println(b3)
b3

[6 7 8; 7 6 5]


2×3 view(::Matrix{Int64}, 2:3, 3:5) with eltype Int64:
 6  7  8
 7  6  5

In [23]:
b3[1,3] = 88         # b3[1,3] is pointing to a[2,5]; modifying it will modify
                     # the original array
a                    # In Python, b3[0,2] is pointing to a[1,4]; 

3×5 Matrix{Int64}:
 1  2  3  4   5
 4  5  6  7  88
 9  8  7  6   5

In [24]:
b4 = a[3:end, :]       # row 3 onwards and all columns
                       # In Python, row 2 onwards and all columns
println(b4)            # b4 is rank 2 (i.e. Matrix)
print(size(b4))        # Output In Python [[9 8 7 6 5]] Observe the double square brackets
b4

[9 8 7 6 5]
(1, 5)

1×5 Matrix{Int64}:
 9  8  7  6  5

In [25]:
b5 = a[3, :]         # row 3 and all columns (:)
                     # In Python, row 2 and all columns
print(b5)            # b5 is rank 1 (i.e. Vector)

[9, 8, 7, 6, 5]

In [26]:
println(size(b5))      # (5,)
b5

(5,)


5-element Vector{Int64}:
 9
 8
 7
 6
 5

# Reshaping Arrays

In Julia, to reshape an array `b5` into a 1-row 2D array, similar to NumPy's `reshape(1, -1)`, use:

```julia
b5_reshaped = reshape(b5, 1, :))
```

This keeps `b5`'s total number of elements, distributing them across 1 row.

In [27]:
b5 = reshape(b5, 1, :)
println(b5)
b5
# Python           Julia
# [[9 8 7 6 5]] is 1×5 Matrix{Int64}:
#                   9  8  7  6  5

[9 8 7 6 5]


1×5 Matrix{Int64}:
 9  8  7  6  5

In [28]:
b4 = vec(b4) # In Python b4.reshape(-1,)

5-element Vector{Int64}:
 9
 8
 7
 6
 5

In Julia, to reshape an array `b4` into a 1-dimensional array (equivalent to Python's `reshape(-1,)`), you can use:

```julia
b4_flat = vec(b4)
```

or

```julia
b4_flat = reshape(b4, :)
```

Both methods will flatten `b4` into a 1D array.

# Array Maths

In [29]:
# Define the arrays
x1 = [1 2 3; 4 5 6]
y1 = [7 8 9; 2 3 4]

# Print the result
println(x1 + y1)
x1 + y1

[8 10 12; 6 8 10]


2×3 Matrix{Int64}:
 8  10  12
 6   8  10

In [30]:
x = [2,3]
y = [4,2]
z = x + y;


In [31]:
x1 + y1

2×3 Matrix{Int64}:
 8  10  12
 6   8  10

In [32]:
@show (x1 .- y1)     # same as np.subtract(x1,y1)
@show (x1 .* y1)     # same as np.multiply(x1,y1)
@show (x1 ./ y1);    # same as np.divide(x1,y1)

x1 .- y1 = [-6 -6 -6; 2 2 2]
x1 .* y1 = [7 16 27; 8 15 24]
x1 ./ y1 = [0.14285714285714285 0.25 0.3333333333333333; 2.0 1.6666666666666667 1.5]


In [33]:
# Define the arrays
names = ["Ann", "Joe", "Mark"]
heights = [1.5, 1.78, 1.6]
weights = [65, 46, 59]

# Calculate the BMI
bmi = weights ./ (heights .^ 2)  # Note the use of broadcasting operators (.^ and ./)

# Print the BMI
println(bmi)                     # [ 28.88888889  14.51836889  23.046875  ]

[28.88888888888889, 14.518368892816563, 23.046874999999996]


In [34]:
println("Overweight: " , names[filter(i -> bmi[i] > 25, 1:length(names))])
println("Underweight: ", names[filter(i -> bmi[i] < 18.5, 1:length(names))])
println("Healthy: "    , names[filter(i -> bmi[i] >= 18.5 && bmi[i] <= 25, 1:length(names))])

Overweight: ["Ann"]
Underweight: ["Joe"]
Healthy: ["Mark"]


# Dot Product

In [35]:
x = [2,3]
y = [4,2]
dot(x,y)  # 2x4 + 3x2 = 14 


14

In [36]:
x2 = [1 2 3; 4 5 6]
y2 = [7 8; 9 10; 11 12]
println(x2 * y2)  # matrix multiplication
x2 * y2


[58 64; 139 154]


2×2 Matrix{Int64}:
  58   64
 139  154

## Matrix

In [37]:
# Define the matrices
x2 = [1 2; 4 5]      # x2 = np.matrix([[1,2],[4,5]])
y2 = [7 8; 2 3];      # y2 = np.matrix([[7,8],[2,3]])


In [38]:
# x1 = np.array([[1,2],[4,5]])
# y1 = np.array([[7,8],[2,3]])
# x1 = np.asmatrix(x1)
# y1 = np.asmatrix(y1)


In Julia, there's no need to convert arrays to a matrix type for matrix operations because Julia's native arrays already support matrix arithmetic, including multiplication, addition, inversion, and more, directly. However, if you're looking for an equivalent way to ensure that your variables are treated specifically as matrices (for example, for clarity or to access certain matrix-specific functions), you can simply work with two-dimensional arrays, as Julia's array type is inherently multidimensional and behaves like a matrix when it has two dimensions.

Here's how you can define and use two-dimensional arrays (matrices) in Julia, equivalent to the Python code you provided:

```julia
# Define the arrays as two-dimensional Julia arrays
x1 = [1 2; 4 5]
y1 = [7 8; 2 3]

# Perform matrix operations directly
# For example, matrix multiplication
result = x1 * y1

# Julia's arrays support matrix operations directly, so there's no need for a separate 'asmatrix' step
println(result)
```

This code defines `x1` and `y1` as two-dimensional arrays and performs matrix multiplication directly with the `*` operator, showcasing the simplicity of matrix operations in Julia without the need for converting array types.

In [39]:
x1 = [1 2; 4 5]     # x1 = np.array([[1,2],[4,5]])
y1 = [7 8; 2 3]     # y1 = np.array([[7,8],[2,3]])
println(x1 .* y1)     # element-by-element multiplication

x2 = [1 2; 4 5]     # x2 = np.matrix([[1,2],[4,5]])
y2 = [7 8; 2 3]     # y2 = np.matrix([[7,8],[2,3]])

println(x2 * y2)    # dot product; same as np.dot()


[7 16; 8 15]
[11 14; 38 47]


## Cumulative Sum

In [40]:
a = [1 2 3;4 5 6;7 8 9]   # a = np.array([(1,2,3),(4,5,6), (7,8,9)])
println(a)
a

[1 2 3; 4 5 6; 7 8 9]


3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [41]:
println(cumsum(vec(transpose(a))))   # prints the cumulative sum of all the
                                     # elements in the array
                                     # [ 1  3  6 10 15 21 28 36 45]
                                     # reshape(transpose(a),:)) can also be used

[1, 3, 6, 10, 15, 21, 28, 36, 45]


&#x1F3F7;   In Julia, arrays are stored in column-major order by default, meaning operations like `reshape` or `vec` will flatten the array in column-major order. To flatten an array by row and then compute the cumulative sum, you can first transpose the array to switch rows and columns, flatten the transposed array, and then apply `cumsum`. Here's how you can do it:

```julia
# Define a 2D array
a = [1 2 3; 4 5 6; 7 8 9]

# Transpose, flatten the array by row, and compute the cumulative sum
cumulative_sum = cumsum(reshape(transpose(a), :))

# Print the result
println(cumulative_sum)
```

In this code:
- `transpose(a)` transposes the array `a`, switching its rows and columns.
- `reshape(transpose(a), :)` flattens the transposed array, effectively flattening `a` by rows due to the prior transposition.
- `cumsum` computes the cumulative sum over this flattened array.

The output will be the cumulative sum as if the array was flattened by rows, not by columns:

```
[1, 3, 6, 10, 15, 21, 28, 36, 45]
```

This result matches the expected behavior of flattening by row in a row-major order context, even though Julia uses column-major order for storage.

In [42]:
println(cumsum(a, dims=1))  # sum over rows for each of the 3 columns


[1 2 3; 5 7 9; 12 15 18]


In [43]:
println(cumsum(a, dims=2))  # sum over columns for each of the 3 rows


[1 3 6; 4 9 15; 7 15 24]


## NumPy Sorting

In [44]:
ages = [34, 12, 37, 5, 13]
sorted_ages = sort(ages)      # does not modify the original array
println(sorted_ages)          # [ 5, 12, 13, 34, 37]
println(ages)                 # [34, 12, 37, 5, 13]


[5, 12, 13, 34, 37]
[34, 12, 37, 5, 13]


In [45]:
sort!(ages)                   # modifies the array
print(ages)                   # [ 5, 12, 13, 34, 37]


[5, 12, 13, 34, 37]

In [46]:
ages = [34, 12, 37, 5, 13]
println(sortperm(ages))         # In Python ages.argsort()
                              # In Python [0-based index] returns [3 1 4 0 2]
                              # In Julia [1-based index] returns [4, 2, 5, 1, 3]

[4, 2, 5, 1, 3]


In Julia, to obtain the indices that would sort an array, you can use the `sortperm` function. This function returns an array of indices that sorts the array. 

This code snippet will output the indices of `ages` that would sort the array. Note that Julia uses `1-based indexing`, so the indices may appear different from Python's 0-based indexing, but the relative ordering is what matters for sorting purposes.

In [47]:
println(ages[sortperm(ages)])   # [5, 12, 13, 34, 37]


[5, 12, 13, 34, 37]


In [48]:
persons = ["Johnny", "Mary", "Peter", "Will", "Joe"]
ages    = [34, 12, 37, 5, 13]
heights = [1.76, 1.2, 1.68, 0.5, 1.25];


In [49]:
sort_indices = sortperm(ages);   # performs a sort based on ages
                                 # and returns an array of indices
                                 # indicating the sort order


In [50]:
println(persons[sort_indices])    # ["Will", "Mary", "Joe", "Johnny", "Peter"]
println(ages[sort_indices])       # [5, 12, 13, 34, 37]
println(heights[sort_indices])    # [0.5, 1.2, 1.25, 1.76, 1.68]


["Will", "Mary", "Joe", "Johnny", "Peter"]
[5, 12, 13, 34, 37]
[0.5, 1.2, 1.25, 1.76, 1.68]


In [51]:
sort_indices = sortperm(persons)   # sort based on names
println(persons[sort_indices])     # ["Joe", "Johnny", "Mary", "Peter", "Will"]
println(ages[sort_indices])        # [13, 34, 12, 37, 5]
println(heights[sort_indices])     # 1.25, 1.76, 1.2, 1.68, 0.5]


["Joe", "Johnny", "Mary", "Peter", "Will"]
[13, 34, 12, 37, 5]
[1.25, 1.76, 1.2, 1.68, 0.5]


In [52]:
reverse_sort_indices = sortperm(persons, rev=true) # reverse the order of a list
println(persons[reverse_sort_indices])             # ["Will", "Peter", "Mary", "Johnny", "Joe"]
println(ages[reverse_sort_indices])                # [5, 37, 12, 34, 13]
println(heights[reverse_sort_indices])             # [0.5, 1.68, 1.2, 1.76, 1.25]


["Will", "Peter", "Mary", "Johnny", "Joe"]
[5, 37, 12, 34, 13]
[0.5, 1.68, 1.2, 1.76, 1.25]


# Array Assignment

## Copying by Reference

In [53]:
list1 = [[1,2,3,4], [5,6,7,8]]
a1 = Array(list1)
println(a1)


[[1, 2, 3, 4], [5, 6, 7, 8]]


In [54]:
a2 = a1             # creates a copy by reference
println(a1)
println(a2)


[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [55]:
a2[1][1] = 11      # make some changes to a2
println(a1)          # affects a1
println(a2)


[[11, 2, 3, 4], [5, 6, 7, 8]]
[[11, 2, 3, 4], [5, 6, 7, 8]]


In [56]:
a1 = reshape(transpose(hcat(a1...)), 1, :) # Reshape to a column vector
a2 = a1  # Now a2 references the reshaped a1
println(a1)
println(a2)         # a2 also changes shape

[11 5 2 6 3 7 4 8]
[11 5 2 6 3 7 4 8]


Given that reshaping in Julia doesn't modify the original array, if you still want `a2` to reflect changes to `a1` (like a reshape), you'd need to work with array views or explicitly set `a2` to the reshaped version of a1 each time. 

## Copying by View (Shallow Copy)

In [57]:
list1 = [[1,2,3,4], [5,6,7,8]]
a1 = Array(list1)
a2 = view(a1,:)    # creates a copy of a1 by reference; but changes
                  # in dimension in a1 will not affect a2
println(a1)
println(a2)


[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [58]:
a1[1][1] = 11     # make some changes in a1
println(a1)
println(a2)         # changes is also seen in a2


[[11, 2, 3, 4], [5, 6, 7, 8]]
[[11, 2, 3, 4], [5, 6, 7, 8]]


In [59]:
a1 = reshape(transpose(hcat(a1...)), 1, :) # Reshape to a column vector
print(a1)
print(a2)         # a2 does not change shape


[11 5 2 6 3 7 4 8][[11, 2, 3, 4], [5, 6, 7, 8]]

## Copying by Value (Deep Copy)

In [60]:
list1 = [[1,2,3,4], [5,6,7,8]]
a1 = Array(list1)
a2 = deepcopy(a1)     # create a copy of a1 by value (deep copy)


2-element Vector{Vector{Int64}}:
 [1, 2, 3, 4]
 [5, 6, 7, 8]

In [61]:
a1[1][1] = 11     # make some changes in a1
println(a1)
println(a2)         # changes is not seen in a2


[[11, 2, 3, 4], [5, 6, 7, 8]]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [62]:
a1 = reshape(transpose(hcat(a1...)), 1, :) # Reshape to a column vector
println(a1)
println(a2)         # a2 does not change shape

[11 5 2 6 3 7 4 8]
[[1, 2, 3, 4], [5, 6, 7, 8]]
