In [2]:
import numpy as np

In [3]:
a = np.array([(1,2,3),(4,5,6), (7,8,9)])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(a.cumsum())

[ 1  3  6 10 15 21 28 36 45]


SyntaxError: invalid syntax. Perhaps you forgot a comma? (3233677360.py, line 2)